fix: use a more robust type guard (#18)
The problem is that when you start playing around with yarn link,
you might end up with multiple instances of the Namer class.

Error looks like:
```
/Users/ahammond/Documents/ClickUp/cold-storage-cdk/node_modules/multi-convention-namer/src/namer.ts:207
    return new Namer([...this.parts, ...s], { ...this.props, ...props });
                                        ^
TypeError: s is not iterable
    at Namer.addSuffix (/Users/ahammond/Documents/ClickUp/cold-storage-cdk/node_modules/multi-convention-namer/src/namer.ts:207:41)
```

Solution? Use `Array.isArray()` instead, since it's core.